//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub mod prelude;

pub mod flyway_schema_history;
pub mod organization;
pub mod repository;
pub mod repository_label;
pub mod repository_revision;
pub mod repository_revision_label;
