//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub use super::flyway_schema_history::Entity as FlywaySchemaHistory;
pub use super::organization::Entity as Organization;
pub use super::repository::Entity as Repository;
pub use super::repository_label::Entity as RepositoryLabel;
pub use super::repository_revision::Entity as RepositoryRevision;
pub use super::repository_revision_label::Entity as RepositoryRevisionLabel;
