---
apiVersion: v1
kind: Service
metadata:
  name: dumont
  namespace: dumont
  labels:
    app: dumont
spec:
  ports:
  - name: http
    targetPort: 3030
    port: 80
  - name: http-metrics
    targetPort: 3031
    port: 3031
  selector:
    app: dumont