//! SeaORM Entity. Generated by sea-orm-codegen 0.4.2

pub mod prelude;

pub mod organization;
pub mod repository;
pub mod repository_label;
pub mod repository_metadata;
pub mod repository_revision;
pub mod repository_revision_label;
