//! SeaORM Entity. Generated by sea-orm-codegen 0.4.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "repository_metadata")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub repository_metadata_id: i32,
    #[sea_orm(unique)]
    pub repo_id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub repo_url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::repository::Entity",
        from = "Column::RepoId",
        to = "super::repository::Column::RepoId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Repository,
}

impl Related<super::repository::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Repository.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
