//! SeaORM Entity. Generated by sea-orm-codegen 0.2.4

pub mod prelude;

pub mod orginization;
pub mod repository;
pub mod repository_labels;
pub mod repository_revision;
pub mod repository_revision_labels;
