//! SeaORM Entity. Generated by sea-orm-codegen 0.2.4

pub use super::orginization::Entity as Orginization;
pub use super::repository::Entity as Repository;
pub use super::repository_labels::Entity as RepositoryLabels;
pub use super::repository_revision::Entity as RepositoryRevision;
pub use super::repository_revision_labels::Entity as RepositoryRevisionLabels;
