//! SeaORM Entity. Generated by sea-orm-codegen 0.2.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "repository_revision")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub revision_id: i32,
    pub repo_id: i32,
    #[sea_orm(column_type = "Text")]
    pub scm_tag: String,
    #[sea_orm(column_type = "Text")]
    pub scm_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::repository::Entity",
        from = "Column::RepoId",
        to = "super::repository::Column::RepoId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Repository,
}

impl Related<super::repository::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Repository.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
